#!/bin/bash
# Start sumulation with NMEA log in first parameter.
# in not get first parameter - with sveden-finland.nmea

if [ -f "$1" ]
then
	NMEAlog=$1
else
	NMEAlog="sveden-finland.nmea"
fi
echo "Trying to start simulation with $NMEAlog"

# For Raspberry Pi !
#sudo systemctl stop gpsd
#sudo systemctl stop gpsd.socket
killall gpsd

BASEDIR=$(dirname "$0")
cd  $BASEDIR

# gpsdPROXY 
if [ -d "/Galadrielmap" ]
then
	DIRprefix="/Galadrielmap"
	cd /Galadrielmap/map/gpsdPROXY
else
	DIRprefix=".."
	cd ../gpsdPROXY
fi
php=$(grep '^$phpCLIexec' params.php) 
# вырезать то, что между кавычками иначе не получается
i=$(expr index "$php" "\['"]\")	# позиция первого вхождения ' или "
php=${php:$i}	# вырезать от i до конца строки
i=$(expr index "$php" "\['"]\")
php=${php:0:$i-1}

$php gpsdPROXY.php > /dev/null 2>&1 &

echo $php $BASEDIR $PWD
# Источник данных
# gpsdPROXY к нему подключится сам
pkill -f naiveNMEAdaemon.php	
cd  $BASEDIR
$php naiveNMEAdaemon.php -t500000 --wind=135,7.5,0.5 --depth=30,0.7 $NMEAlog > /dev/null 2>&1 &
sleep 1
gpsd -G -n tcp://localhost:2222


# netAIS, demo server
pkill -f eqavt5cdur7vbzoejquiwviok4tfexy32sggxdxujm75uiljqi5g27ad.onion
cd $DIRprefix/netAIS
$php netAISclient.php -seqavt5cdur7vbzoejquiwviok4tfexy32sggxdxujm75uiljqi5g27ad.onion > /dev/null 2>&1 &


# inetAIS - AIS из интернета. После gpsdPROXY
#if ! pgrep -f inetAIS.php  > /dev/null	# следует указать возможно полную строку для поиска, ибо в пути тоже может быть та же фраза, и тогда будет весело
#then
	#/GaladrielMap/digitraffic/start -d
#	../digitraffic/start -d
#fi
# Но проще так:
pkill -f inetAIS.php
cd  $BASEDIR
$DIRprefix/digitraffic/start -d

echo "Simulation started. Probably."
