#!/bin/bash
/GaladrielMap/digitraffic/start -d
php /GaladrielMap/map/samples/naiveNMEAdaemon.php -t500000 --wind=135,7.5,0.5 --depth=7,0.7 /GaladrielMap/map/samples/sveden-finland.nmea > /dev/null 2>&1 &
sleep 1
#gpsd -G -n tcp://0.0.0.0:2222
#GPSD_SOCKET=/tmp/gpsd.sock
#GPSD_SOCKET=/var/run/gpsd.socket
#gpsdctl add tcp://0.0.0.0:2222
# wit unetAIS
gpsd -G -n tcp://0.0.0.0:2222 tcp://0.0.0.0:3800
#gpsdctl add tcp://0.0.0.0:3800
echo "Boat simulation started"

