#!/bin/bash
# 
# 

# For Raspberry Pi !
#sudo systemctl stop gpsd
#sudo systemctl stop gpsd.socket
killall gpsd
pkill -f inetAIS.php
pkill -f naiveNMEAdaemon.php	
pkill -f eqavt5cdur7vbzoejquiwviok4tfexy32sggxdxujm75uiljqi5g27ad.onion

echo "Simulation stopped. Probably."
